TARpe21ShopHõbesalu/Models/OpenWeather/OpenWeatherViewModel.cs
namespace TARpe21ShopHõbesalu.Models.OpenWeather
{
    public class OpenWeatherViewModel
    {
        public string City { get; set; }
        public double Temperature { get; set; }
        public int AirPressure { get; set; }
        public int AirHumidity { get; set; }
        public string Main { get; set; }
        public double WindSpeed { get; set; }
    }
}

TARpe21ShopHõbesalu/Controllers/OpenWeatherController.cs
using Microsoft.AspNetCore.Mvc;
using TARpe21ShopHõbesalu.Core.Dto.WeatherDtos;
using TARpe21ShopHõbesalu.Core.ServiceInterface;
using TARpe21ShopHõbesalu.Models.OpenWeather;

namespace TARpe21ShopHõbesalu.Controllers
{
    public class OpenWeatherController : Controller
    {
        private readonly IWeatherForecastsServices _openWeatherServices;
        public OpenWeatherController(IWeatherForecastsServices weatherForecastServices)
        {
            _openWeatherServices = weatherForecastServices;
        }

        public IActionResult Index()
        {
            OpenWeatherViewModel vm = new OpenWeatherViewModel();
            return View(vm);
        }

        [HttpPost]
        public IActionResult ShowWeather()
        {
            string city = Request.Form["City"];

            if (!string.IsNullOrEmpty(city))
            {
                OpenWeatherResultDto dto = new();
                dto.City = city;
                _openWeatherServices.OpenWeatherDetail(dto);

                OpenWeatherViewModel vm = new()
                {
                    City = dto.City,

                    Temperature = dto.Temperature,
                    AirPressure = dto.AirPressure,
                    AirHumidity = dto.AirHumidity,
                    Main = dto.Main,

                    WindSpeed = dto.WindSpeed
                };

                return View("City", vm);
            }

            return View();
        }
    }
}

TARpe21ShopHõbesalu/Views/OpenWeather/City.cshtml
@model TARpe21ShopHõbesalu.Models.OpenWeather.OpenWeatherViewModel
<!DOCTYPE html>
<html>
<head>
    <title>Weather Forecast</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #eff7ff; 
        }

    </style>
</head>
<body>
    <h1>City</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Forecast for the selected city</h2>
                <hr />
                <dl class="row">
                    <dt class="col-sm-5">City</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.City)</dd>

                    <dt class="col-sm-5">Temperature</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.Temperature)</dd>

                    <dt class="col-sm-5">Air Pressure</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.AirPressure)</dd>

                    <dt class="col-sm-5">Air Humidity</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.AirHumidity)</dd>

                    <dt class="col-sm-5">Main</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.Main)</dd>

                    <dt class="col-sm-5">Wind Speed</dt>
                    <dd class="col-sm-7">@Html.DisplayFor(model => model.WindSpeed)</dd>
                </dl>
            </div>
        </div>
    </div>
</body>
</html>

TARpe21ShopHõbesalu/Views/OpenWeather/Index.cshtml
<form method="post" asp-action="ShowWeather" asp-controller="OpenWeather">
    <div class="form-group col-md-offset-7 col-md-7">
        <h2>Search up a city to see its weather</h2>
    </div>
    <br />
    <div class="container">
        <input type="text" name="City" value="" />
        <input type="submit" class="btn btn-primary" value="Lets see the weather" />
    </div>
</form>